networks:
  devops:
    external: false

services:
  nginx:
    image: nginx:latest
    container_name: nginx_service
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - devops
    depends_on:
      - gitea
      - jenkins

  gitea:
    image: gitea/gitea:1.22.3
    container_name: gitea_service
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=postgres_db:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=${GITEA_DB_PASSWD}
      - GITEA__webhook__ALLOWED_HOST_LIST=jenkins_service_devops,172.23.164.166,jenkins.net
    restart: always
    networks:
      - devops
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres:14
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=gitea
    networks:
      - devops
    volumes:
      - ./postgres:/var/lib/postgresql/data

  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins_service
    environment:
      - JENKINS_PREFIX=/jenkins
    user: root
    ports:
      - "8080:8080" # Jenkins UI
      - "50000:50000" # Para agentes remotos
    networks:
      - devops
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
